----
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: foaas-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: foaas-svc
    servicePort: http