apiVersion: v1
kind: Service
metadata:
  name: foaas-svc
  annotations:
    "consul.hashicorp.com/service-sync": "false"
    "consul.hashicorp.com/service-name": foaas-consul-service
    "consul.hashicorp.com/service-tags": "foaas-svc,k8s-service"
  labels:
    app: foaas
spec:
  type: NodePort
  ports:
  - name: http
    port: 30001
    targetPort: http
    protocol: TCP
  selector:
    app: foaas