apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foaas-deploy
  labels:
    app: foaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foaas
  template:
    metadata:
      labels:
        app: foaas
    spec:
      containers:
      - name: foaas-pod
        image: juliashub/foaas:latest
        labels:
          name: foaas-pod
        ports:
        - name: http
          protocol: TCP
          containerPort: 5000