apiVersion: v1
kind: Service
metadata:
  name: foaas-service
  annotations:
    consul.hashicorp.com/service-name: "foaas"
    consul.hashicorp.com/service-tags: "foaas-svc,k8s-service"
    consul.hashicorp.com/service-port: "http"
  labels:
    k8s-app: foaas
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 30001
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: foaas