apiVersion: v1
kind: Service
metadata:
  name: foaas-svc
  labels:
    app: foaas
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 30001
    targetPort: http
    protocol: TCP
  selector:
    app: foaas