---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
        - path: /prometheus
          backend:
            serviceName: prometheus-server
            servicePort: 9090

